### ISSUE TITLE
Does it support ECS with EC2 launch type instead of Fargate?

### ISSUE THREAD

**Issue by JoHuang** [simplygenius/atmos#2]
As title.
Thanks

**Comment by wr0ngway** [comment]
I do support ECS with EC2 instances, but currently only in the pro version.

**Comment by wr0ngway** [comment]
I apologize, I shouldn't have closed this issue.  Since I do have an implementation in the pro version, it is unlikely that I will be reimplementing it here, but that doesn't mean that someone else won't, and this issue should track the desire for its presence.  I may merge in part of the implementation in the future as well.

**Comment by wr0ngway** [comment]
Ok, I merged in the recipes that allow ECS with EC2.
Give it a shot if still interested.
